name: Deploy Test GCP

on: 
  push: 
    branches: 
      - "master"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 34.101.224.73
          username: komangsuryasedana
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /home/komangsuryasedana/gcp
            git pull
            pm2 restart all
